export default [
    {
        fullName: 'Белюга Татьяна Сергеева',
        post: 'Генеральный директор',
        sex: 'Женский',
        department: 'Правление',
        dateOfBirth: new Date('1980, 04, 04'),
        salary: 500000,
        company: 'Тензор',
    },
    {
        fullName: 'Антонов Алексей Максимович',
        post: 'Программист',
        sex: 'Мужской',
        department: 'Разработка',
        dateOfBirth: new Date('1994, 02, 12'),
        salary: 300000,
        company: 'Тензор',
    },
    {
        fullName: 'Коровина Наталия Александровна',
        post: 'Технолог',
        sex: 'Женский',
        department: 'Реклама',
        dateOfBirth: new Date('2002, 11, 02'),
        salary: 150000,
        company: 'Тензор',
    },
    {
        fullName: 'Жмутецкий Виктор Евгеньевич',
        post: 'Менеджер',
        sex: 'Мужской',
        department: 'Реклама',
        dateOfBirth: new Date('1990, 06, 21'),
        salary: 100000,
        company: 'Тензор',
    },
    {
        fullName: 'Химич Евгений Александрович',
        post: 'Исполнительный директор',
        sex: 'Мужской',
        department: 'Правление',
        dateOfBirth: new Date('1980, 04, 04'),
        salary: 450000,
        company: 'Контур',
    },
    {
        fullName: 'Диковец Мария Дмитриевна',
        post: 'Уборщик',
        sex: 'Женский',
        department: 'АХО',
        dateOfBirth: new Date('1980, 04, 04'),
        salary: 13000,
        company: 'Контур',
    },
    {
        fullName: 'Анашкин Петр Иванович',
        post: 'Учитель',
        sex: 'Мужской',
        department: 'Реклама',
        dateOfBirth: new Date('1980, 04, 04'),
        salary: 12000,
        company: 'Контур',
    },
];
