export default {
    '--text-color': '#000000',
    '--icon-color': '#333333',
    '--contrast_text-color': '#ffffff',
    '--link_text-color': '#2562aa',
    '--background-color': '#ffffff',
    '--border-color': '#d2d6da',
    '--separator_color': '#f0f0f0',
    '--label_text-color': '#8991a9',

    '--primary_color': '#ff7033',
    '--primary_text-color': '#cc3d00',
    '--primary_hover_text-color': '#e27140',
    '--primary_icon-color': '#f47843',
    '--primary_hover_icon-color': '#db4200',
    '--primary_border-color': '#ff621f',
    '--primary_background-color': '#fff8f5',
    '--primary_hover_background-color': '#fff1eb',
    '--primary_active_background-color': '#ffe6db',
    '--primary_same_background-color': '#fff1eb',
    '--primary_hover_same_background-color': '#ffe6db',
    '--primary_active_same_background-color': '#ffdbcc',
    '--primary_contrast_background-color': '#f6733c',
    '--primary_hover_contrast_background-color': '#e4662f',
    '--primary_active_contrast_background-color': '#d6551f',
    '--marker_color': '#cc3d00',

    '--secondary_color': '#587ab0',
    '--secondary_text-color': '#313e78',
    '--secondary_hover_text-color': '#2562aa',
    '--secondary_icon-color': '#656c87',
    '--secondary_hover_icon-color': '#153f6f',
    '--secondary_border-color': '#1b579d',
    '--secondary_background-color': '#f5faff',
    '--secondary_hover_background-color': '#ebf4ff',
    '--secondary_active_background-color': '#dbecff',
    '--secondary_same_background-color': '#ebf4ff',
    '--secondary_hover_same_background-color': '#dbecff',
    '--secondary_active_same_background-color': '#cce4ff',
    '--secondary_contrast_background-color': '#265fa1',
    '--secondary_hover_contrast_background-color': '#2b5688',
    '--secondary_active_contrast_background-color': '#274c77',

    '--readonly_marker-color': '#ffdbcc',

    '--unaccented_color': '#999999',
    '--unaccented_text-color': '#999999',
    '--unaccented_hover_text-color': '#6b6b6b',
    '--unaccented_icon-color': '#cccccc',
    '--unaccented_hover_icon-color': '#999',

    '--unaccented_contrast_background-color': '#dbdbdb',
    '--unaccented_hover_contrast_background-color': '#ccc',
    '--unaccented_active_contrast_background-color': '#d4d4d4',

    '--unaccented_background-color': '#f8f8f8',
    '--unaccented_hover_background-color': '#f5f5f5',
    '--active_background-color': '#edeef2',

    '--unaccented_same_background-color': '#eceeee',
    '--pale_contrast_background-color': '#eceeee',
    '--pale_border-color': '#e5e7eb',

    '--danger_color': '#d04d4d',
    '--danger_text-color': '#c2140a',
    '--danger_hover_text-color': '#e50c00',
    '--danger_icon-color': '#c2140a',
    '--danger_hover_icon-color': '#e50c00',
    '--danger_border-color': '#e50c00',
    '--danger_background-color': '#fff7f7',
    '--danger_hover_background-color': '#ffeceb',
    '--danger_active_background-color': '#ffdddb',
    '--danger_same_background-color': '#ffeceb',
    '--danger_hover_same_background-color': '#ffdddb',
    '--danger_active_same_background-color': '#ffcfcc',
    '--danger_contrast_background-color': '#dc2219',
    '--danger_hover_contrast_background-color': '#c22219',
    '--danger_active_contrast_background-color': '#aa2018',

    '--success_color': '#069922',
    '--success_text-color': '#298e3c',
    '--success_hover_text-color': '#28bd44',
    '--success_icon-color': '#298e3c',
    '--success_hover_icon-color': '#28bd44',
    '--success_border-color': '#00a31f',
    '--success_background-color': '#f7fff8',
    '--success_hover_background-color': '#ebffee',
    '--success_active_background-color': '#dbffe2',
    '--success_same_background-color': '#ecf9ec',
    '--success_hover_same_background-color': '#e0f5e0',
    '--success_active_same_background-color': '#d5f1d5',
    '--success_contrast_background-color': '#12a12c',
    '--success_hover_contrast_background-color': '#128c29',
    '--success_active_contrast_background-color': '#127d26',

    '--warning_color': '#fec63f',
    '--warning_text-color': '#e6a119',
    '--warning_hover_text-color': '#f6c055',
    '--warning_icon-color': '#e6a119',
    '--warning_hover_icon-color': '#f6c055',
    '--warning_border-color': '#ffb92e',
    '--warning_background-color': '#fffcf7',
    '--warning_hover_background-color': '#fff8eb',
    '--warning_active_background-color': '#fff3db',
    '--warning_same_background-color': '#fff8eb',
    '--warning_hover_same_background-color': '#fff3db',
    '--warning_active_same_background-color': '#fec',
    '--warning_contrast_background-color': '#ecb956',
    '--warning_hover_contrast_background-color': '#e5ab38',
    '--warning_active_contrast_background-color': '#df9f20',

    '--info_color': '#5a49ab',
    '--info_text-color': '#5a49ab',
    '--info_hover_text-color': '#7e70c2',
    '--info_icon-color': '#5a49ab',
    '--info_hover_icon-color': '#7270c2',
    '--info_border-color': '#513bbf',
    '--info_background-color': '#f8f7ff',
    '--info_hover_background-color': '#eeebff',
    '--info_active_background-color': '#e1dbff',
    '--info_same_background-color': '#eeebff',
    '--info_hover_same_background-color': '#e1dbff',
    '--info_active_same_background-color': '#d4ccff',
    '--info_contrast_background-color': '#6757b7',
    '--info_hover_contrast_background-color': '#5949a7',
    '--info_active_contrast_background-color': '#504294',

    '--notice-center_background-color': '#ecedee',
    '--notice-center_hover_background-color': '#f1f2f5',
};
