export const contractorData = [
    {
        id: 1,
        department: 'Разработка',
        currentTab: '2',
        owner: 'Новиков Д.В.',
        title: 'Разработка',
    },
    {
        id: 2,
        department: 'Продвижение СБИС',
        currentTab: '2',
        owner: 'Кошелев А.Е.',
        title: 'Продвижение СБИС',
    },
    {
        id: 3,
        department: 'Федеральная клиентская служка',
        currentTab: '2',
        owner: 'Мануйлова Ю.А.',
        title: 'Федеральная клиентская служка',
    },
    {
        id: 4,
        department: 'Служба эксплуатации',
        currentTab: '2',
        owner: 'Субботин А.В.',
        title: 'Служба эксплуатации',
    },
    {
        id: 5,
        department: 'Технологии и маркетинг',
        currentTab: '2',
        owner: 'Чеперегин А.С.',
        title: 'Технологии и маркетинг',
    },
    {
        id: 6,
        department: 'Федеральный центр продаж. Call-центр Ярославль',
        currentTab: '2',
        owner: 'Кошелев А.Е.',
        title: 'Федеральный центр продаж. Call-центр Ярославль',
    },
    {
        id: 7,
        department: 'Сопровождение информационных систем',
        currentTab: '2',
        owner: 'Кошелев А.Е.',
        title: 'Сопровождение информационных систем',
    },
];

export const companyData = [
    {
        id: 8,
        title: 'Наша компания',
        currentTab: '1',
        city: null,
        description: 'Управленческая структура',
        active: true,
    },
    {
        id: 9,
        title: 'Все юридические лица',
        currentTab: '1',
        city: null,
        description: null,
        active: true,
    },
    {
        id: 10,
        title: 'Инори, ООО',
        currentTab: '1',
        city: 'г. Ярославль',
        description: null,
        active: true,
    },
    {
        id: 11,
        title: '"Компания "Тензор" ООО',
        currentTab: '1',
        city: 'г. Ярославль',
        description: null,
        active: true,
    },
    {
        id: 12,
        title: 'Ромашка, ООО',
        currentTab: '1',
        city: 'г. Москва',
        description: null,
        active: false,
    },
    {
        id: 13,
        title: 'Сбербанк-Финанс, ООО',
        currentTab: '1',
        city: 'г. Пермь',
        description: null,
        active: true,
    },
    {
        id: 14,
        title: 'Петросоюз-Континент, ООО',
        currentTab: '1',
        city: 'г. Самара',
        description: null,
        active: false,
    },
    {
        id: 15,
        title: 'Альфа Директ сервис, ОАО',
        currentTab: '1',
        city: 'г. Москва',
        description: null,
        active: true,
    },
    {
        id: 16,
        title: 'АК "ТРАНСНЕФТЬ", ОАО',
        currentTab: '1',
        city: 'г. Москва',
        description: null,
        active: false,
    },
    {
        id: 17,
        title: 'Иванова Зинаида Михайловна, ИП',
        currentTab: '1',
        city: 'г. Яросалвль',
        description: null,
        active: true,
    },
];

export const employees = [
    {
        id: 0,
        title: 'Dima',
        node: null,
        closed: true,
        parent: null,
    },
    {
        id: 1,
        title: 'Aleksey',
        node: null,
        closed: true,
        parent: null,
    },
    {
        id: 2,
        title: 'Sasha',
        node: null,
        closed: true,
        parent: null,
    },
];
