export { INameOptionsType, FieldTypes } from './_interface/base/INameOptionsType';
export { ISizeOptionsType } from './_interface/base/ISizeOptionsType';
export { ITableOptionsType } from './_interface/base/ITableOptionsType';
export { IPlaceholderOptionsType } from './_interface/base/IPlaceholderOptionsType';
export { IRequiredOptionsType } from './_interface/base/IRequiredOptionsType';
export { IUseGroupingOptionsType } from './_interface/base/IUseGroupingOptionsType';
export { IConstraintOptionsType } from './_interface/input/IConstraintOptionsType';
export { IDefaultValueOptionsType } from './_interface/input/IDefaultValueOptionsType';
export { IDefaultPhoneValueOptionsType } from './_interface/input/IDefaultPhoneValueOptionsType';
export { IDefaultInputValueOptionsType } from './_interface/input/IDefaultInputValueOptionsType';
export { IDefaultValueOptionsType as IDateDefaultValueOptionsType } from './_interface/date/IDefaultValueOptionsType';
export { ILabelOptionsType } from './_interface/input/ILabelOptionsType';
export { ILengthOptionsType } from './_interface/input/ILengthOptionsType';
export { IMaskOptionsType } from './_interface/input/IMaskOptionsType';
export { IDateMaskType } from './_interface/date/IDateMaskType';
export { IMultilineOptionsType } from './_interface/input/IMultilineOptionsType';
export { INoJumpingLabelOptionsType } from './_interface/input/INoJumpingLabelOptionsType';
export { INumberLengthOptionsType } from './_interface/input/INumberLengthOptionsType';
export { IIntegersLengthOptionsType } from './_interface/input/IIntegersLengthOptionsType';
export { IPrecisionOptionsType } from './_interface/input/IPrecisionOptionsType';
export { IOnlyPositiveOptionsType } from './_interface/input/IOnlyPositiveOptionsType';
export { IPhoneType } from './_interface/input/IPhoneType';
export { IRichTextOptionsType } from './_interface/input/IRichTextOptionsType';
export { ILimitOptionsType } from './_interface/input/ILimitOptionsType';
export { ILimitOptionsType as IDateLimitOptionsType } from './_interface/date/ILimitOptionsType';
export { IRangeLimitOptionsType } from './_interface/date/IRangeLimitOptionsType';
export { IDefaultTimeValueOptionsType } from './_interface/date/IDefaultTimeValueOptionsType';
export { ITimeLimitOptionsType } from './_interface/date/ITimeLimitOptionsType';
export { ITimeIntervalType } from './_interface/date/ITimeIntervalType';
export { IDefaultRangeValueOptionsType } from './_interface/date/IDefaultRangeValueOptionsType';
export { IWrapTextOptionsType } from './_interface/checkboxGroup/IWrapTextOptionsType';
export { IRequiredOptionsType as ICheckboxRequiredOptionsType } from './_interface/checkboxGroup/IRequiredOptionsType';
export { IValidatorOptionsType } from './_interface/base/IValidatorOptionsType';
export { TOrientationType } from './_interface/radioGroup/TOrientationType';
export { TRadioGroupVariantsType } from './_interface/radioGroup/TRadioGroupVariantsType';
export { TComboboxVariantsType } from './_interface/combobox/TComboboxVariantsType';
export { IMultiSelectType } from './_interface/combobox/IMultiSelectType';
export { IVisibleItemsCountType } from './_interface/combobox/IVisibleItemsCountType';
// кнопки
export { ICaptionTypeMeta } from './_interface/button/ICaptionTypeMeta';
export { IIconType } from './_interface/button/IIconType';
export { IIconOptionsType } from './_interface/button/IIconOptionsType';
export { ITooltipTypeMeta } from './_interface/button/ITooltipTypeMeta';
export { IActionTypeMeta } from './_interface/button/IActionTypeMeta';
// TODO: разобраться, почему у RadioGroup и CheckboxGroup свой мета-тип на метку
// https://online.sbis.ru/opendoc.html?guid=35a9a3cd-50a3-499b-816d-0e1d1812214a&client=3
export { ILabelOptionsType as ICheckboxGroupLabelOptionsType } from './_interface/checkboxGroup/ILabelOptionsType';
export { ILabelOptionsType as IRadioGroupLabelOptionsType } from './_interface/radioGroup/ILabelOptionsType';
export { ILabelOptionsType as IComboboxLabelOptionsType } from './_interface/combobox/ILabelOptionsType';
