const coef = [
    { name: 'text_color', S: 1, L: 1 },
    { name: 'text_hover', S: 1.4, L: 0.7 },
    { name: 'link_color', S: 1.95, L: 0.82 },
    { name: 'link_hover', S: 1.7, L: 0.6 },
    { name: 'heading_color', S: 1.7, L: 0.6 },
    { name: 'heading_hover', S: 1.95, L: 0.82 },
    { name: 'icon_color', S: 1.05, L: 1.15 },
    { name: 'icon_hover', S: 1.4, L: 0.7 },
    { name: 'border_color', S: 1.05, L: 1.15 },
    { name: 'border_hover', S: 1.4, L: 0.7 },
    { name: 'fill_color', S: 1.5, L: 1.25 },
    { name: 'fill_hover', S: 1.6, L: 1.16 },
    { name: 'fill_active', S: 1.92, L: 1.32 },
    { name: 'bg_fill_color', S: 100, L: 96, isStrict: true },
    { name: 'bg_fill_hover', S: 100, L: 93, isStrict: true },
    { name: 'bg_fill_active', S: 100, L: 90, isStrict: true },
    { name: 'background_color', S: 100, L: 98, isStrict: true },
    { name: 'background_hover', S: 100, L: 96, isStrict: true },
    { name: 'background_active', S: 100, L: 93, isStrict: true },
];

const coefAcc = [
    { name: 'bg', S: 1, L: 1 },
    { name: 'bg_hover', S: 0.83, L: 1.35 },
    { name: 'bg_selected', S: 1.05, L: 0.9 },
    { name: 'bg_selected_hover', S: 0.83, L: 1.35 },
    { name: 'menu_fill', S: 0.83, L: 1.35 },
    { name: 'menu_hover', S: 0.87, L: 1.25 },
    { name: 'counter', S: 1, L: 0.95 },
    { name: 'counter_ hover', S: 0.9, L: 1.09 },
    { name: 'counter_ on_menu_hover', S: 0.83, L: 1.25 },
    { name: 'counter_selected', S: 1, L: 1.1 },
    { name: 'counter_selected_hover', S: 0.83, L: 1.35 },
    { name: 'counter_ on_selected_menu_hover', S: 0.83, L: 1.37 },
    { name: 'fill_plus', S: 0.83, L: 1.37 },
    { name: 'fill_plus_hover', S: 0.9, L: 1.09 },
    { name: 'icon-plus', S: 0.9, L: 1.09 },
    { name: 'icon-plus_hover', S: 0.9, L: 1.09 },
    { name: 'menu_plus_fill', S: 0.83, L: 1.37 },
    { name: 'menu_plus_hover', S: 0.9, L: 1.09 },
    { name: 'open_button_fill', S: 1, L: 0.95 },
    { name: 'open_button_hover', S: 0.9, L: 1.09 },
    { name: 'open_hover_on_menu', S: 0.83, L: 1.25 },
    { name: 'footer_button', S: 0.87, L: 1.25 },
    { name: 'footer_button_hover', S: 0.87, L: 1.25 },
    { name: 'footer_arrow_icon', S: 1.1, L: 2.87 },
    { name: 'footer_arrow_icon_hover', S: 2.73, L: 3.45 },
    { name: 'Icons', S: 1, L: 2.9 },
    { name: 'Icons_hover', S: 1, L: 2.9 },
    { name: 'Icons_selected', S: 0, L: 4.15 },
];

export { coef, coefAcc };
