import { Memory } from 'Types/source';
import { RecordSet } from 'Types/collection';
import { Model } from 'Types/entity';
import { getColumns } from './Data';
import { TItemActionShowType } from 'Controls/_itemActions/constants';
import { getMoreActions } from 'Controls-demo/list_new/DemoHelpers/ItemActionsCatalog';

export interface TItem {
    key: string | number;
    country: string;
    capital: string;
    group: string;
}

export function getData(count?: number): TItem[] {
    return [
        {
            key: 0,
            country: 'Afghanistan',
            capital: 'Kabul',
            group: 'Asia',
        },
        {
            key: 1,
            country: 'Albania',
            capital: 'Tirana (Tirane)',
            group: 'Europe',
        },
        {
            key: 2,
            country: 'Algeria',
            capital: 'Algiers',
            group: 'Africa',
        },
        {
            key: 3,
            country: 'Andorra',
            capital: 'Andorra la Vella',
            group: 'Europe',
        },
        {
            key: 4,
            country: 'Angola',
            capital: 'Luanda',
            group: 'Africa',
        },
        {
            key: 5,
            country: 'Antigua and Barbuda',
            capital: "Saint John's",
            group: 'Antigua and Barbuda',
        },
        {
            key: 6,
            country: 'Argentina',
            capital: 'Buenos Aires',
            group: 'South America',
        },
        {
            key: 7,
            country: 'Armenia',
            capital: 'Yerevan',
            group: 'Asia',
        },
        {
            key: 8,
            country: 'Australia',
            capital: 'Canberra',
            group: 'Australia',
        },
        {
            key: 9,
            country: 'Austria',
            capital: 'Vienna',
            group: 'Europe',
        },
        {
            key: 10,
            country: 'Azerbaijan',
            capital: 'Baku',
            group: 'Asia',
        },
        {
            key: 11,
            country: 'Bahamas',
            capital: 'Nassau',
            group: 'Bahamas',
        },
        {
            key: 12,
            country: 'Bahrain',
            capital: 'Manama',
            group: 'Asia',
        },
        {
            key: 13,
            country: 'Bangladesh',
            capital: 'Dhaka',
            group: 'Asia',
        },
        {
            key: 14,
            country: 'Barbados',
            capital: 'Bridgetown',
            group: 'Caribbean Sea',
        },
        {
            key: 15,
            country: 'Belarus',
            capital: 'Minsk',
            group: 'CONTROLS_HIDDEN_GROUP',
        },
        {
            key: 16,
            country: 'Belgium',
            capital: 'Brussels',
            group: 'Europe',
        },
        {
            key: 17,
            country: 'Belize',
            capital: 'Belmopan',
            group: 'Caribbean Sea',
        },
        {
            key: 18,
            country: 'Benin',
            capital: 'Porto Novo',
            group: 'Africa',
        },
        {
            key: 19,
            country: 'Bhutan',
            capital: 'Thimphu',
            group: 'Asia',
        },
        {
            key: 20,
            country: 'Bolivia',
            capital: 'La Paz (administrative), Sucre (official)',
            group: 'South America',
        },
        {
            key: 21,
            country: 'Bosnia and Herzegovina',
            capital: 'Sarajevo',
            group: 'Europe',
        },
        {
            key: 22,
            country: 'Botswana',
            capital: 'Gaborone',
            group: 'Africa',
        },
        {
            key: 23,
            country: 'Brazil',
            capital: 'Brasilia',
            group: 'South America',
        },
        {
            key: 24,
            country: 'Brunei',
            capital: 'Bandar Seri Begawan',
            group: 'Asia',
        },
        {
            key: 25,
            country: 'Bulgaria',
            capital: 'Sofia',
            group: 'Europe',
        },
        {
            key: 26,
            country: 'Burkina Faso',
            capital: 'Ouagadougou',
            group: 'Africa',
        },
        {
            key: 27,
            country: 'Burundi',
            capital: 'Gitega',
            group: 'Africa',
        },
        {
            key: 28,
            country: 'Cambodia',
            capital: 'Phnom Penh',
            group: 'Asia',
        },
        {
            key: 29,
            country: 'Cameroon',
            capital: 'Yaounde',
            group: 'Africa',
        },
        {
            key: 30,
            country: 'Canada',
            capital: 'Ottawa',
            group: 'North America',
        },
        {
            key: 31,
            country: 'Cape Verde',
            capital: 'Praia',
            group: 'Africa',
        },
        {
            key: 32,
            country: 'Central African Republic',
            capital: 'Bangui',
            group: 'Africa',
        },
        {
            key: 33,
            country: 'Chad',
            capital: "N'Djamena",
            group: 'Africa',
        },
        {
            key: 34,
            country: 'Chile',
            capital: 'Santiago',
            group: 'South America',
        },
        {
            key: 35,
            country: 'China',
            capital: 'Beijing',
            group: 'Asia',
        },
        {
            key: 36,
            country: 'Colombia',
            capital: 'Bogota',
            group: 'South America',
        },
        {
            key: 37,
            country: 'Comoros',
            capital: 'Moroni',
            group: 'Africa',
        },
        {
            key: 38,
            country: 'Congo, Democratic Republic of the',
            capital: 'Kinshasa',
            group: 'Africa',
        },
        {
            key: 39,
            country: 'Congo, Republic of the',
            capital: 'Brazzaville',
            group: 'Africa',
        },
        {
            key: 40,
            country: 'Costa Rica',
            capital: 'San Jose',
            group: 'South America',
        },
        {
            key: 41,
            country: "Côte d'Ivoire (Ivory Coast)",
            capital: 'Yamoussoukro',
            group: 'Africa',
        },
        {
            key: 42,
            country: 'Croatia',
            capital: 'Zagreb',
            group: 'Europe',
        },
        {
            key: 43,
            country: 'Cuba',
            capital: 'Havana',
            group: 'Caribbean Sea',
        },
        {
            key: 44,
            country: 'Cyprus',
            capital: 'Nicosia',
            group: 'Europe',
        },
        {
            key: 45,
            country: 'Czech Republic (Czechia)',
            capital: 'Prague',
            group: 'Europe',
        },
        {
            key: 46,
            country: 'Denmark',
            capital: 'Copenhagen',
            group: 'Europe',
        },
        {
            key: 47,
            country: 'Djibouti',
            capital: 'Djibouti',
            group: 'Africa',
        },
        {
            key: 48,
            country: 'Dominica',
            capital: 'Roseau',
            group: 'Caribbean Sea',
        },
        {
            key: 49,
            country: 'Dominican Republic',
            capital: 'Santo Domingo',
            group: 'Caribbean Sea',
        },
        {
            key: 50,
            country: 'East Timor',
            capital: 'Dili',
            group: 'Asia',
        },
        {
            key: 51,
            country: 'Ecuador',
            capital: 'Quito',
            group: 'South America',
        },
        {
            key: 52,
            country: 'Egypt',
            capital: 'Cairo',
            group: 'Africa',
        },
        {
            key: 53,
            country: 'El Salvador',
            capital: 'San Salvador',
            group: 'America',
        },
        {
            key: 54,
            country: 'England',
            capital: 'London',
            group: 'Europe',
        },
        {
            key: 55,
            country: 'Equatorial Guinea',
            capital: 'Malabo',
            group: 'Africa',
        },
        {
            key: 56,
            country: 'Eritrea',
            capital: 'Asmara',
            group: 'Africa',
        },
        {
            key: 57,
            country: 'Estonia',
            capital: 'Tallinn',
            group: 'Europe',
        },
        {
            key: 58,
            country: 'Eswatini (Swaziland)',
            capital: 'Mbabana',
            group: 'Africa',
        },
        {
            key: 59,
            country: 'Ethiopia',
            capital: 'Addis Ababa',
            group: 'Africa',
        },
        {
            key: 60,
            country: 'Federated States of Micronesia',
            capital: 'Palikir',
            group: 'Africa',
        },
        {
            key: 61,
            country: 'Fiji',
            capital: 'Suva',
            group: 'Oceania',
        },
        {
            key: 62,
            country: 'Finland',
            capital: 'Helsinki',
            group: 'Europe',
        },
        {
            key: 63,
            country: 'France',
            capital: 'Paris',
            group: 'Europe',
        },
        {
            key: 64,
            country: 'Gabon',
            capital: 'Libreville',
            group: 'Africa',
        },
        {
            key: 65,
            country: 'Gambia',
            capital: 'Banjul',
            group: 'Africa',
        },
        {
            key: 66,
            country: 'Georgia',
            capital: 'Tbilisi',
            group: 'Europe',
        },
        {
            key: 67,
            country: 'Germany',
            capital: 'Berlin',
            group: 'Europe',
        },
        {
            key: 68,
            country: 'Ghana',
            capital: 'Accra',
            group: 'Africa',
        },
        {
            key: 69,
            country: 'Greece',
            capital: 'Athens',
            group: 'Europe',
        },
        {
            key: 70,
            country: 'Grenada',
            capital: "Saint George's",
            group: 'Caribbean Sea',
        },
        {
            key: 71,
            country: 'Guatemala',
            capital: 'Guatemala City',
            group: 'America',
        },
        {
            key: 72,
            country: 'Guinea',
            capital: 'Conakry',
            group: 'Africa',
        },
        {
            key: 73,
            country: 'Guinea-Bissau',
            capital: 'Bissau',
            group: 'Africa',
        },
        {
            key: 74,
            country: 'Guyana',
            capital: 'Georgetown',
            group: 'South America',
        },
        {
            key: 75,
            country: 'Haiti',
            capital: 'Port au Prince',
            group: 'Caribbean Sea',
        },
        {
            key: 76,
            country: 'Honduras',
            capital: 'Tegucigalpa',
            group: 'America',
        },
        {
            key: 77,
            country: 'Hungary',
            capital: 'Budapest',
            group: 'Europe',
        },
        {
            key: 78,
            country: 'Iceland',
            capital: 'Reykjavik',
            group: 'Europe',
        },
        {
            key: 79,
            country: 'India',
            capital: 'New Delhi',
            group: 'Asia',
        },
        {
            key: 80,
            country: 'Indonesia',
            capital: 'Jakarta',
            group: 'Asia',
        },
        {
            key: 81,
            country: 'Iran',
            capital: 'Tehran',
            group: 'Middle East',
        },
        {
            key: 82,
            country: 'Iraq',
            capital: 'Baghdad',
            group: 'Middle East',
        },
        {
            key: 83,
            country: 'Ireland',
            capital: 'Dublin',
            group: 'Europe',
        },
        {
            key: 84,
            country: 'Israel',
            capital: 'Jerusalem (very limited international recognition)',
            group: 'Middle East',
        },
        {
            key: 85,
            country: 'Italy',
            capital: 'Rome',
            group: 'Europe',
        },
        {
            key: 86,
            country: 'Jamaica',
            capital: 'Kingston',
            group: 'Caribbean Sea',
        },
        {
            key: 87,
            country: 'Japan',
            capital: 'Tokyo',
            group: 'Asia',
        },
        {
            key: 88,
            country: 'Jordan',
            capital: 'Amman',
            group: 'Middle East',
        },
        {
            key: 89,
            country: 'Kazakhstan',
            capital: 'Astana',
            group: 'CONTROLS_HIDDEN_GROUP',
        },
        {
            key: 90,
            country: 'Kenya',
            capital: 'Nairobi',
            group: 'Africa',
        },
        {
            key: 91,
            country: 'Kiribati',
            capital: 'Tarawa Atoll',
            group: 'Oceania',
        },
        {
            key: 92,
            country: 'Kosovo',
            capital: 'Pristina',
            group: 'Europe',
        },
        {
            key: 93,
            country: 'Kuwait',
            capital: 'Kuwait City',
            group: 'Middle East',
        },
        {
            key: 94,
            country: 'Kyrgyzstan',
            capital: 'Bishkek',
            group: 'Asia',
        },
        {
            key: 95,
            country: 'Laos',
            capital: 'Vientiane',
            group: 'Asia',
        },
        {
            key: 96,
            country: 'Latvia',
            capital: 'Riga',
            group: 'Europe',
        },
        {
            key: 97,
            country: 'Lebanon',
            capital: 'Beirut',
            group: 'Middle East',
        },
        {
            key: 98,
            country: 'Lesotho',
            capital: 'Maseru',
            group: 'Africa',
        },
        {
            key: 99,
            country: 'Liberia',
            capital: 'Monrovia',
            group: 'Africa',
        },
        {
            key: 100,
            country: 'Libya',
            capital: 'Tripoli',
            group: 'Africa',
        },
        {
            key: 101,
            country: 'Liechtenstein',
            capital: 'Vaduz',
            group: 'Europe',
        },
        {
            key: 102,
            country: 'Lithuania',
            capital: 'Vilnius',
            group: 'Europe',
        },
        {
            key: 103,
            country: 'Luxembourg',
            capital: 'Luxembourg',
            group: 'Europe',
        },
        {
            key: 104,
            country: 'Madagascar',
            capital: 'Antananarivo',
            group: 'Africa',
        },
        {
            key: 105,
            country: 'Malawi',
            capital: 'Lilongwe',
            group: 'Africa',
        },
        {
            key: 106,
            country: 'Malaysia',
            capital: 'Kuala Lumpur',
            group: 'Asia',
        },
        {
            key: 107,
            country: 'Maldives',
            capital: 'Male',
            group: 'Asia',
        },
        {
            key: 108,
            country: 'Mali',
            capital: 'Bamako',
            group: 'Africa',
        },
        {
            key: 109,
            country: 'Malta',
            capital: 'Valletta',
            group: 'Europe',
        },
        {
            key: 110,
            country: 'Marshall Islands',
            capital: 'Majuro',
            group: 'Oceania',
        },
        {
            key: 111,
            country: 'Mauritania',
            capital: 'Nouakchott',
            group: 'Africa',
        },
        {
            key: 112,
            country: 'Mauritius',
            capital: 'Port Louis',
            group: 'Africa',
        },
        {
            key: 113,
            country: 'Mexico',
            capital: 'Mexico City',
            group: 'North America',
        },
        {
            key: 114,
            country: 'Moldova',
            capital: 'Chisinau',
            group: 'Europe',
        },
        {
            key: 115,
            country: 'Monaco',
            capital: 'Monaco',
            group: 'Europe',
        },
        {
            key: 116,
            country: 'Mongolia',
            capital: 'Ulaanbaatar',
            group: 'Asia',
        },
        {
            key: 117,
            country: 'Montenegro',
            capital: 'Podgorica',
            group: 'Europe',
        },
        {
            key: 118,
            country: 'Morocco',
            capital: 'Rabat',
            group: 'Africa',
        },
        {
            key: 119,
            country: 'Mozambique',
            capital: 'Maputo',
            group: 'Africa',
        },
        {
            key: 120,
            country: 'Myanmar (Burma)',
            capital: 'Nay Pyi Taw',
            group: 'Asia',
        },
        {
            key: 121,
            country: 'Namibia',
            capital: 'Windhoek',
            group: 'Africa',
        },
        {
            key: 122,
            country: 'Nauru',
            capital: 'No official capital',
            group: 'Oceania',
        },
        {
            key: 123,
            country: 'Nepal',
            capital: 'Kathmandu',
            group: 'Asia',
        },
        {
            key: 124,
            country: 'Netherlands',
            capital: 'Amsterdam',
            group: 'Europe',
        },
        {
            key: 125,
            country: 'New Zealand',
            capital: 'Wellington',
            group: 'Oceania',
        },
        {
            key: 126,
            country: 'Nicaragua',
            capital: 'Managua',
            group: 'America',
        },
        {
            key: 127,
            country: 'Niger',
            capital: 'Niamey',
            group: 'Africa',
        },
        {
            key: 128,
            country: 'Nigeria',
            capital: 'Abuja',
            group: 'Africa',
        },
        {
            key: 129,
            country: 'North Korea',
            capital: 'Pyongyang',
            group: 'Asia',
        },
        {
            key: 130,
            country: 'North Macedonia (Macedonia)',
            capital: 'Skopje',
            group: 'Europe',
        },
        {
            key: 131,
            country: 'Northern Ireland',
            capital: 'Belfast',
            group: 'Europe',
        },
        {
            key: 132,
            country: 'Norway',
            capital: 'Oslo',
            group: 'Europe',
        },
        {
            key: 133,
            country: 'Oman',
            capital: 'Muscat',
            group: 'Middle East',
        },
        {
            key: 134,
            country: 'Pakistan',
            capital: 'Islamabad',
            group: 'Asia',
        },
        {
            key: 135,
            country: 'Palau',
            capital: 'Melekeok',
            group: 'Oceania',
        },
        {
            key: 136,
            country: 'Palestine',
            capital: 'Jerusalem (very limited international recognition)',
            group: 'Middle East',
        },
        {
            key: 137,
            country: 'Panama',
            capital: 'Panama City',
            group: 'America',
        },
        {
            key: 138,
            country: 'Papua New Guinea',
            capital: 'Port Moresby',
            group: 'Oceania',
        },
        {
            key: 139,
            country: 'Paraguay',
            capital: 'Asuncion',
            group: 'South America',
        },
        {
            key: 140,
            country: 'Peru',
            capital: 'Lima',
            group: 'South America',
        },
        {
            key: 141,
            country: 'Philippines',
            capital: 'Manila',
            group: 'Asia',
        },
        {
            key: 142,
            country: 'Poland',
            capital: 'Warsaw',
            group: 'Europe',
        },
        {
            key: 143,
            country: 'Portugal',
            capital: 'Lisbon',
            group: 'Europe',
        },
        {
            key: 144,
            country: 'Qatar',
            capital: 'Doha',
            group: 'Middle East',
        },
        {
            key: 145,
            country: 'Romania',
            capital: 'Bucharest',
            group: 'Europe',
        },
        {
            key: 146,
            country: 'Russia',
            capital: 'Moscow',
            group: 'CONTROLS_HIDDEN_GROUP',
        },
        {
            key: 147,
            country: 'Rwanda',
            capital: 'Kigali',
            group: 'Africa',
        },
        {
            key: 148,
            country: 'Saint Kitts and Nevis',
            capital: 'Basseterre',
            group: 'Caribbean Sea',
        },
        {
            key: 149,
            country: 'Saint Lucia',
            capital: 'Castries',
            group: 'Caribbean Sea',
        },
        {
            key: 150,
            country: 'Saint Vincent and the Grenadines',
            capital: 'Kingstown',
            group: 'Caribbean Sea',
        },
        {
            key: 151,
            country: 'Samoa',
            capital: 'Apia',
            group: 'Oceania',
        },
        {
            key: 152,
            country: 'San Marino',
            capital: 'San Marino',
            group: 'Europe',
        },
        {
            key: 153,
            country: 'Sao Tome and Principe',
            capital: 'Sao Tome',
            group: 'America',
        },
        {
            key: 154,
            country: 'Saudi Arabia',
            capital: 'Riyadh',
            group: 'Middle East',
        },
        {
            key: 155,
            country: 'Scotland',
            capital: 'Edinburgh',
            group: 'Europe',
        },
        {
            key: 156,
            country: 'Senegal',
            capital: 'Dakar',
            group: 'Africa',
        },
        {
            key: 157,
            country: 'Serbia',
            capital: 'Belgrade',
            group: 'Europe',
        },
        {
            key: 158,
            country: 'Seychelles',
            capital: 'Victoria',
            group: 'Africa',
        },
        {
            key: 159,
            country: 'Sierra Leone',
            capital: 'Freetown',
            group: 'Africa',
        },
        {
            key: 160,
            country: 'Singapore',
            capital: 'Singapore',
            group: 'Asia',
        },
        {
            key: 161,
            country: 'Slovakia',
            capital: 'Bratislava',
            group: 'Europe',
        },
        {
            key: 162,
            country: 'Slovenia',
            capital: 'Ljubljana',
            group: 'Europe',
        },
        {
            key: 163,
            country: 'Solomon Islands',
            capital: 'Honiara',
            group: 'Oceania',
        },
        {
            key: 164,
            country: 'Somalia',
            capital: 'Mogadishu',
            group: 'Africa',
        },
        {
            key: 165,
            country: 'South Africa',
            capital: 'Pretoria, Bloemfontein, Cape Town',
            group: 'Africa',
        },
        {
            key: 166,
            country: 'South Korea',
            capital: 'Seoul',
            group: 'Asia',
        },
        {
            key: 167,
            country: 'South Sudan',
            capital: 'Juba',
            group: 'Africa',
        },
        {
            key: 168,
            country: 'Spain',
            capital: 'Madrid',
            group: 'Europe',
        },
        {
            key: 169,
            country: 'Sri Lanka',
            capital: 'Sri Jayawardenapura Kotte',
            group: 'Asia',
        },
        {
            key: 170,
            country: 'Sudan',
            capital: 'Khartoum',
            group: 'Africa',
        },
        {
            key: 171,
            country: 'Suriname',
            capital: 'Paramaribo',
            group: 'South America',
        },
        {
            key: 172,
            country: 'Sweden',
            capital: 'Stockholm',
            group: 'Europe',
        },
        {
            key: 173,
            country: 'Switzerland',
            capital: 'Bern',
            group: 'Europe',
        },
        {
            key: 174,
            country: 'Syria',
            capital: 'Damascus',
            group: 'Middle East',
        },
        {
            key: 175,
            country: 'Taiwan',
            capital: 'Taipei',
            group: 'Asia',
        },
        {
            key: 176,
            country: 'Tajikistan',
            capital: 'Dushanbe',
            group: 'Asia',
        },
        {
            key: 177,
            country: 'Tanzania',
            capital: 'Dodoma',
            group: 'Africa',
        },
        {
            key: 178,
            country: 'Thailand',
            capital: 'Bangkok',
            group: 'Asia',
        },
        {
            key: 179,
            country: 'Togo',
            capital: 'Lome',
            group: 'Africa',
        },
        {
            key: 180,
            country: 'Tonga',
            capital: "Nuku'alofa",
            group: 'Oceania',
        },
        {
            key: 181,
            country: 'Trinidad and Tobago',
            capital: 'Port of Spain',
            group: 'Caribbean Sea',
        },
        {
            key: 182,
            country: 'Tunisia',
            capital: 'Tunis',
            group: 'Africa',
        },
        {
            key: 183,
            country: 'Türkiye (Turkey)',
            capital: 'Ankara',
            group: 'Middle East',
        },
        {
            key: 184,
            country: 'Turkmenistan',
            capital: 'Ashgabat',
            group: 'Asia',
        },
        {
            key: 185,
            country: 'Tuvalu',
            capital: 'Funafuti',
            group: 'Oceania',
        },
        {
            key: 186,
            country: 'Uganda',
            capital: 'Kampala',
            group: 'Africa',
        },
        {
            key: 187,
            country: 'Ukraine',
            capital: 'Kyiv or Kiev',
            group: 'Europe',
        },
        {
            key: 188,
            country: 'United Arab Emirates',
            capital: 'Abu Dhabi',
            group: 'Middle East',
        },
        {
            key: 189,
            country: 'United Kingdom',
            capital: 'London',
            group: 'Europe',
        },
        {
            key: 190,
            country: 'United States',
            capital: 'Washington D.C.',
            group: 'North America',
        },
        {
            key: 191,
            country: 'Uruguay',
            capital: 'Montevideo',
            group: 'South America',
        },
        {
            key: 192,
            country: 'Uzbekistan',
            capital: 'Tashkent',
            group: 'Asia',
        },
        {
            key: 193,
            country: 'Vanuatu',
            capital: 'Port Vila',
            group: 'Oceania',
        },
        {
            key: 194,
            country: 'Vatican City',
            capital: 'Vatican City',
            group: 'Europe',
        },
        {
            key: 195,
            country: 'Venezuela',
            capital: 'Caracas',
            group: 'South America',
        },
        {
            key: 196,
            country: 'Vietnam',
            capital: 'Hanoi',
            group: 'Asia',
        },
        {
            key: 197,
            country: 'Wales',
            capital: 'Cardiff',
            group: 'Europe',
        },
        {
            key: 198,
            country: 'Yemen',
            capital: "Sana'a",
            group: 'Middle East',
        },
        {
            key: 199,
            country: 'Zambia',
            capital: 'Lusaka',
            group: 'Africa',
        },
        {
            key: 200,
            country: 'Zimbabwe',
            capital: 'Harare',
            group: 'Africa',
        },
    ].slice(0, count);
}

export function getDataWithItemActions() {
    return [
        {
            key: 0,
            country: 'Afghanistan',
            capital: 'Kabul',
            group: 'Asia',
            itemActions: getMoreActions(),
        },
        {
            key: 1,
            country: 'Albania',
            capital: 'Tirana (Tirane)',
            group: 'Europe',
            itemActions: getMoreActions(),
        },
        {
            key: 2,
            country: 'Algeria',
            capital: 'Algiers',
            group: 'Africa',
            itemActions: getMoreActions(),
        },
        {
            key: 3,
            country: 'Andorra',
            capital: 'Andorra la Vella',
            group: 'Europe',
            itemActions: getMoreActions(),
        },
        {
            key: 4,
            country: 'Angola',
            capital: 'Luanda',
            group: 'Africa',
            itemActions: getMoreActions(),
        },
        {
            key: 5,
            country: 'Antigua and Barbuda',
            capital: "Saint John's",
            group: 'Antigua and Barbuda',
            itemActions: getMoreActions(),
        },
        {
            key: 6,
            country: 'Argentina',
            capital: 'Buenos Aires',
            group: 'South America',
            itemActions: getMoreActions(),
        },
        {
            key: 7,
            country: 'Armenia',
            capital: 'Yerevan',
            group: 'Asia',
            itemActions: getMoreActions(),
        },
        {
            key: 8,
            country: 'Australia',
            capital: 'Canberra',
            group: 'Australia',
            itemActions: getMoreActions(),
        },
        {
            key: 9,
            country: 'Austria',
            capital: 'Vienna',
            group: 'Europe',
            itemActions: getMoreActions(),
        },
        {
            key: 10,
            country: 'Azerbaijan',
            capital: 'Baku',
            group: 'Asia',
            itemActions: getMoreActions(),
        },
    ];
}

function getMetaData(): Record<string, unknown> {
    return {
        results: new Model({
            rawData: {
                count: 200,
                populationCountries: 7888000001,
                populationCapitals: 1442563023,
            },
        }),
    };
}

export function getSource(): Memory {
    return new Memory({
        keyProperty: 'key',
        data: getData(),
    });
}

export function getItems(count?: number): RecordSet {
    return new RecordSet({
        keyProperty: 'key',
        rawData: count ? getData().slice(0, count) : getData(),
        metaData: getMetaData(),
    });
}

export function getItemsWithItemActions(count?: number): RecordSet {
    return new RecordSet({
        keyProperty: 'key',
        rawData: count ? getDataWithItemActions().slice(0, count) : getDataWithItemActions(),
        metaData: getMetaData(),
    });
}

export { getColumns };
