import { RecordSet } from 'Types/collection';

export const getData = (): RecordSet => {
    return new RecordSet({
        rawData: [
            {
                key: 1,
                date: '30.04.21',
                time: '10:32',
                name: 'Константинов К. А.',
                group: 'Платформа',
            },
            {
                key: 2,
                date: '30.04.21',
                time: '13:52',
                name: 'Александров А. А.',
                group: 'Платформа',
            },
            {
                key: 3,
                date: '30.04.21',
                time: '13:53',
                name: 'Иванов И. И.',
                group: 'Платформа',
            },
            {
                key: 4,
                date: '30.04.21',
                time: '15:45',
                name: 'Вадимов В. В.',
                group: 'Платформа',
            },
            {
                key: 5,
                date: '26.04.21',
                time: '14:32',
                name: 'Сергеев С. С.',
                group: 'Платформа',
            },
            {
                key: 6,
                date: '14.03.21',
                time: '16:33',
                name: 'Дмитриев Д. Д.',
                group: 'Платформа',
            },
            {
                key: 7,
                date: '14.03.21',
                time: '20:02',
                name: 'Еленина Е. Е.',
                group: 'Платформа',
            },
            {
                key: 8,
                date: '14.03.21',
                time: '21:32',
                name: 'Мариева М. М.',
                group: 'Платформа',
            },
            {
                key: 9,
                date: '14.03.21',
                time: '21:34',
                name: 'Анастасьева А. А.',
                group: 'Платформа',
            },
            {
                key: 10,
                date: '22.02.21',
                time: '16:32',
                name: 'Олегов О. О.',
                group: 'Документооборот и УЦ',
            },
            {
                key: 11,
                date: '22.02.21',
                time: '18:00',
                name: 'Николаев Н. Н.',
                group: 'Документооборот и УЦ',
            },
            {
                key: 12,
                date: '22.02.21',
                time: '20:00',
                name: 'Татьянина Т. Т.',
                group: 'Документооборот и УЦ',
            },
            {
                key: 13,
                date: '22.02.21',
                time: '22:00',
                name: 'Алексеев А. А.',
                group: 'Документооборот и УЦ',
            },
            {
                key: 14,
                date: '23.02.21',
                time: '09:00',
                name: 'Ирина И. И.',
                group: 'Документооборот и УЦ',
            },
            {
                key: 15,
                date: '23.02.21',
                time: '11:00',
                name: 'Светланова С. С.',
                group: 'Документооборот и УЦ',
            },
            {
                key: 16,
                date: '23.02.21',
                time: '18:00',
                name: 'Викторов В. В.',
                group: 'Документооборот и УЦ',
            },
            {
                key: 17,
                date: '24.02.21',
                time: '10:00',
                name: 'Романов Р. Р.',
                group: 'Бухгалтерия',
            },
            {
                key: 18,
                date: '24.02.21',
                time: '12:15',
                name: 'Кириллов К. К.',
                group: 'Бухгалтерия',
            },
            {
                key: 19,
                date: '24.02.21',
                time: '14:45',
                name: 'Денисов Д. Д.',
                group: 'Бухгалтерия',
            },
            {
                key: 20,
                date: '25.02.21',
                time: '09:30',
                name: 'Евгеньев Е. Е.',
                group: 'Бухгалтерия',
            },
            {
                key: 21,
                date: '25.02.21',
                time: '16:00',
                name: 'Анатольев А. А.',
                group: 'Бухгалтерия',
            },
            {
                key: 22,
                date: '26.02.21',
                time: '11:30',
                name: 'Григорьев Г. Г.',
                group: 'Дизайн',
            },
            {
                key: 23,
                date: '26.02.21',
                time: '13:15',
                name: 'Ольгина О. О.',
                group: 'Дизайн',
            },
            {
                key: 24,
                date: '26.02.21',
                time: '15:45',
                name: 'Станиславов С. С.',
                group: 'Дизайн',
            },
            {
                key: 25,
                date: '27.02.21',
                time: '09:00',
                name: 'Тимуров Т. Т.',
                group: 'Дизайн',
            },
            {
                key: 26,
                date: '27.02.21',
                time: '17:30',
                name: 'Людмилина Л. Л.',
                group: 'Дизайн',
            },
            {
                key: 27,
                date: '27.02.21',
                time: '17:30',
                name: 'Тимуров Т. Т.',
                group: 'Дизайн',
            },
            {
                key: 28,
                date: '27.02.21',
                time: '17:30',
                name: 'Антонов А. А.',
                group: 'Дизайн',
            },
            {
                key: 29,
                date: '28.02.21',
                time: '10:00',
                name: 'Аринина А. А.',
                group: 'Каталоги',
            },
            {
                key: 30,
                date: '28.02.21',
                time: '14:30',
                name: 'Натальина Н. Н.',
                group: 'Каталоги',
            },
            {
                key: 31,
                date: '28.02.21',
                time: '16:45',
                name: 'Сергеев С. С.',
                group: 'Каталоги',
            },
            {
                key: 32,
                date: '01.03.21',
                time: '09:00',
                name: 'Екатеринина Е. Е.',
                group: 'Каталоги',
            },
        ],
        keyProperty: 'key',
    });
};
export const getColumns = () => {
    return [
        {
            width: 'max-content',
            displayProperty: 'date',
        },
        {
            displayProperty: 'time',
            width: '150px',
        },
        {
            displayProperty: 'name',
            width: '250px',
        },
        {
            displayProperty: 'group',
            width: 'auto',
        },
    ];
};
export const getHeader = () => {
    return [{ caption: 'Дата' }, { caption: 'Время' }, { caption: 'Имя' }, { caption: 'Сектор' }];
};
