export function getData() {
    return [
        {
            key: 1,
            node: true,
            category: 'Электроника',
            description: 'Раздел с различной электроникой',
            parent: null,
        },
        {
            key: 11,
            node: true,
            category: 'Компьютеры',
            description: 'Все о компьютерах и комплектующих',
            parent: 1,
        },
        {
            key: 111,
            node: true,
            category: 'Ноутбуки',
            description: 'Ноутбуки различных брендов и моделей',
            parent: 11,
        },
        {
            key: 1111,
            node: null,
            category: 'Игровые Ноутбуки',
            description: 'Ноутбуки для игр с высокой производительностью',
            parent: 111,
        },
        {
            key: 1112,
            node: null,
            category: 'Ультрабуки',
            description: 'Тонкие и легкие ноутбуки для повседневного использования',
            parent: 111,
        },
        {
            key: 112,
            node: true,
            category: 'Настольные ПК',
            description: 'Настольные компьютеры для работы и игр',
            parent: 11,
        },
        {
            key: 1121,
            node: null,
            category: 'Игровые ПК',
            description: 'Настольные компьютеры, оптимизированные для игр',
            parent: 112,
        },
        {
            key: 1122,
            node: null,
            category: 'Офисные ПК',
            description: 'Настольные компьютеры для офисной работы',
            parent: 112,
        },
        {
            key: 113,
            node: true,
            category: 'Аксессуары',
            description: 'Аксессуары для компьютеров и ноутбуков',
            parent: 1,
        },
        {
            key: 114,
            node: null,
            category: 'Клавиатуры',
            description: 'Различные клавиатуры для ПК и ноутбуков',
            parent: 113,
        },
        {
            key: 1141,
            node: null,
            category: 'Механические Клавиатуры',
            description: 'Клавиатуры с механическими переключателями',
            parent: 114,
        },
        {
            key: 1142,
            node: null,
            category: 'Силиконовые Клавиатуры',
            description: 'Гибкие клавиатуры для удобства использования',
            parent: 114,
        },
        {
            key: 115,
            node: null,
            category: 'Мыши',
            description: 'Мыши для компьютеров и ноутбуков',
            parent: 113,
        },
        {
            key: 1151,
            node: null,
            category: 'Игровые Мыши',
            description: 'Мыши с высокой чувствительностью для игр',
            parent: 115,
        },
        {
            key: 1152,
            node: null,
            category: 'Обычные Мыши',
            description: 'Стандартные мыши для повседневного использования',
            parent: 115,
        },
        // New objects added below
        {
            key: 12,
            node: true,
            category: 'Телевизоры',
            description: 'Современные телевизоры с различными технологиями отображения',
            parent: 1,
        },
        {
            key: 121,
            node: true,
            category: 'Смарт-ТВ',
            description: 'Телевизоры с функциями Smart TV',
            parent: 12,
        },
        {
            key: 1211,
            node: null,
            category: '4K Смарт-ТВ',
            description: 'Телевизоры с разрешением 4K для четкого изображения',
            parent: 121,
        },
        {
            key: 1212,
            node: null,
            category: 'HD Смарт-ТВ',
            description: 'Телевизоры с разрешением HD для хорошего качества изображения',
            parent: 121,
        },
        {
            key: 122,
            node: null,
            category: 'LED Телевизоры',
            description: 'Телевизоры с LED подсветкой для яркого изображения',
            parent: 12,
        },
        {
            key: 13,
            node: true,
            category: 'Смартфоны',
            description: 'Современные смартфоны различных брендов и моделей',
            parent: 1,
        },
        {
            key: 131,
            node: true,
            category: 'Android Смартфоны',
            description: 'Смартфоны на платформе Android от различных производителей',
            parent: 13,
        },
        {
            key: 1311,
            node: null,
            category: 'Samsung',
            description: 'Смартфоны Samsung на платформе Android',
            parent: 131,
        },
        {
            key: 1312,
            node: null,
            category: 'Xiaomi',
            description: 'Смартфоны Xiaomi на платформе Android',
            parent: 131,
        },
        {
            key: 132,
            node: true,
            category: 'iPhone',
            description: 'Смартфоны Apple iPhone с уникальными характеристиками',
            parent: 13,
        },
        {
            key: 14,
            node: true,
            category: 'Планшеты',
            description: 'Разнообразные планшеты для работы и развлечений',
            parent: 1,
        },
        {
            key: 141,
            node: true,
            category: 'Android Планшеты',
            description: 'Планшеты на платформе Android',
            parent: 14,
        },
        {
            key: 1411,
            node: null,
            category: 'Samsung Планшеты',
            description: 'Планшеты Samsung на платформе Android',
            parent: 141,
        },
        {
            key: 1412,
            node: null,
            category: 'Huawei Планшеты',
            description: 'Планшеты Huawei на платформе Android',
            parent: 141,
        },
        {
            key: 142,
            node: null,
            category: 'iPad',
            description: 'Планшеты Apple iPad с высоким качеством сборки',
            parent: 14,
        },
        {
            key: 15,
            node: true,
            category: 'Наушники',
            description: 'Наушники различных типов и брендов',
            parent: 1,
        },
        {
            key: 151,
            node: true,
            category: 'Беспроводные Наушники',
            description: 'Наушники без проводов для удобства использования',
            parent: 15,
        },
        {
            key: '1511',
            node: null,
            category: 'Bluetooth Наушники',
            description: 'Наушники с Bluetooth подключением',
            parent: '151',
        },
        {
            key: '1512',
            node: null,
            category: 'Наушники с NFC',
            description: 'Наушники с поддержкой NFC подключения',
            parent: '151',
        },
        {
            key: '152',
            node: null,
            category: 'Наушники с проводом',
            description: 'Классические наушники с проводным подключением',
            parent: '15',
        },
    ];
}
