import { IMAGE_GREEN, IMAGE_PHONE, IMAGE_PHONE2 } from './images';

export const data = [
    {
        key: 1,
        title: 'Телефоны',
        parent: null,
        type: true,
        hasChild: true,
    },
    {
        key: 11,
        title: 'Apple',
        parent: 1,
        type: true,
        hasChild: true,
        image: IMAGE_PHONE,
    },
    {
        key: 111,
        title: 'IPhone XR',
        parent: 11,
        type: null,
        image: IMAGE_PHONE,
    },
    {
        key: 112,
        title: 'IPhone XS',
        parent: 11,
        type: null,
        image: IMAGE_PHONE,
    },
    {
        key: 113,
        title: 'Iphone 12',
        parent: 11,
        type: null,
        image: IMAGE_PHONE,
    },
    {
        key: 12,
        title: 'Samsung',
        parent: 1,
        type: true,
        hasChild: true,
    },
    {
        key: 124,
        title: 'Galaxy S24',
        parent: 12,
        type: null,
        image: IMAGE_GREEN,
    },
    {
        key: 121,
        title: 'Galaxy S25',
        parent: 12,
        type: null,
        image: IMAGE_GREEN,
    },
    {
        key: 125,
        title: 'Galaxy S25+',
        parent: 12,
        type: null,
        image: IMAGE_GREEN,
    },
    {
        key: 13,
        title: 'Huawei',
        parent: 1,
        type: true,
        hasChild: true,
    },
    {
        key: 131,
        title: 'Mate 70 Pro',
        parent: 13,
        type: null,
        image: IMAGE_PHONE2,
    },
    {
        key: 132,
        title: 'Pura 70 Ultra',
        parent: 13,
        type: null,
        image: IMAGE_PHONE2,
    },
];
