export default {
    '--primary_color': '#e44766',
    '--primary_hover_text-color': '#d1002a',
    '--primary_background-color': '#fff5f7',
    '--primary_hover_background-color': '#ffebef',
    '--primary_active_background-color': '#ffdbe2',
    '--primary_same_background-color': '#ffebef',
    '--primary_hover_same_background-color': '#ffdbe2',
    '--primary_active_same_background-color': '#ffccd6',
    '--primary_hover_contrast_background-color': '#dd2044',
    '--marker_color': '#e44766',
    '--secondary_border-color': '#8991a9',
    '--secondary_icon-color': '#999999',
    '--secondary_hover_icon-color': '#474747',
};
