export const itemsWithUsed = [
    { key: '1', title: 'НД по прибыли', node: null, parent: null },
    { key: '2', title: 'Персонифицированные сведения', node: null, parent: null },
    { key: '3', title: 'Уведомление о налогах для ЕНП', node: null, parent: null },
    { key: '4', title: 'НД по НДС', node: null, parent: null, used: true },
    { key: '5', title: 'НД по УСН', node: null, parent: null, used: true },
    { key: '6', title: 'Налоговая', node: true, parent: null },
    { key: '7', title: 'Расчет по страховым взносам', node: null, parent: '6' },
    { key: '8', title: 'Книга УСН', node: null, parent: '6' },
    { key: '9', title: 'Бухгалтерская (финансовая) отчетность', node: null, parent: '6' },
    { key: '10', title: '6 - НДФЛ', node: null, parent: '6', used: true },
    {
        key: '11',
        title: 'НД по налогу на имущество организаций',
        node: null,
        parent: '6',
        used: true,
    },
    { key: '12', title: 'Название или КНД', node: null, parent: '6' },
    { key: '13', title: 'Заявление к косвенным налогам', node: null, parent: '6' },
    {
        key: '14',
        title: 'Отчет о финансовых результатах деятельности учреждения',
        node: null,
        parent: '6',
    },
    { key: '15', title: 'НД по косвенным налогам', node: null, parent: '6', used: true },
    { key: '16', title: 'Журнал учета счетов-фактур', node: null, parent: '6' },
    { key: '17', title: 'НД по акцизам - табачные изделия', node: null, parent: '6' },
];
