export function getData() {
    return [
        {
            key: 1,
            title: 'Apple',
            country: 'США',
            rating: '8.5',
            parent: null,
            type: true,
        },
        {
            key: 11,
            title: 'Notebooks',
            country: 'США',
            rating: '8.5',
            parent: 1,
            type: false,
        },
        {
            key: 12,
            title: 'IPhones',
            country: 'США',
            rating: '8.5',
            parent: 1,
            type: false,
        },
        {
            key: 121,
            title: 'IPhone XS',
            country: 'США',
            rating: '8.5',
            parent: 12,
            type: null,
        },
        {
            key: 122,
            title: 'IPhone X',
            country: 'США',
            rating: '8.5',
            parent: 12,
            type: null,
        },
        {
            key: 123,
            title: 'IPhone XS Max',
            country: 'США',
            rating: '8.5',
            parent: 12,
            type: null,
        },
        {
            key: 124,
            title: 'IPhone 8',
            country: 'США',
            rating: '8.5',
            parent: 12,
            type: null,
        },
        {
            key: 13,
            title: 'iPad Air 2015',
            country: 'США',
            rating: '8.5',
            parent: 1,
            type: null,
        },
        {
            key: 14,
            title: 'iPad Air 2017',
            country: 'США',
            rating: '8.5',
            parent: 1,
            type: null,
        },
    ];
}
