/**
 * @kaizen_zone 039c82f1-a0a3-4548-82d6-c9e1dbaf5de0
 */
export enum ActionsNames {
    MOVE = 'MOVE',
    NEXT_DISPLAY = 'NEXT_DISPLAY',
    PREV_DISPLAY = 'PREV_DISPLAY',
    SEND_COMMAND_STARTED = 'SEND_COMMAND_STARTED',
    SEND_COMMAND_SUCCEEDED = 'SEND_COMMAND_SUCCEEDED',
    SEND_COMMAND_FAILED = 'SEND_COMMAND_FAILED',
    RECEIVE_EVENT_GROUP = 'RECEIVE_EVENT_GROUP',
    OPEN_CONNECTION_STARTED = 'OPEN_CONNECTION_STARTED',
    OPEN_CONNECTION_SUCCEEDED = 'OPEN_CONNECTION_SUCCEEDED',
    OPEN_CONNECTION_FAILED = 'OPEN_CONNECTION_FAILED',
    CLOSE_CONNECTION_STARTED = 'CLOSE_CONNECTION_STARTED',
    CLOSE_CONNECTION_SUCCEEDED = 'CLOSE_CONNECTION_SUCCEEDED',
    CLOSE_CONNECTION_FAILED = 'CLOSE_CONNECTION_FAILED',
}
