import * as explorerImages from 'Controls-demo/Explorer/ExplorerImagesLayout';

export const data = [
    {
        key: 0,
        parent: null,
        type: null,
        title: 'Папка',
        image: explorerImages[8],
        'parent@': true,
        imageProportion: '1:1',
        imageViewMode: 'circle',
        imagePosition: 'top',
    },
    {
        key: 1,
        parent: null,
        type: null,
        title: 'Папка',
        image: explorerImages[8],
        'parent@': true,
        imageProportion: '1:1',
        imageViewMode: 'rectangle',
        imagePosition: 'top',
    },
    {
        key: 2,
        parent: null,
        type: null,
        title: 'Папка',
        image: explorerImages[8],
        'parent@': true,
        imageProportion: '1:1',
        imageViewMode: 'ellipse',
        imagePosition: 'top',
    },
    {
        key: 3,
        parent: null,
        'parent@': null,
        type: null,
        title: 'Запись',
        image: explorerImages[8],
        description: 'Элемент с описанием',
        imageProportion: '1:1',
        imagePosition: 'top',
        imageViewMode: 'circle',
    },
    {
        key: 4,
        parent: null,
        'parent@': null,
        type: null,
        title: 'Запись',
        image: explorerImages[8],
        description: 'Элемент с описанием',
        imageProportion: '1:1',
        imagePosition: 'top',
        imageViewMode: 'rectangle',
    },
    {
        key: 5,
        parent: null,
        'parent@': null,
        type: null,
        title: 'Запись',
        image: explorerImages[8],
        description: 'Элемент с описанием',
        imageProportion: '1:1',
        imagePosition: 'top',
        imageViewMode: 'ellipse',
    },
];
