export const COMMON_PROPS = {
    roundAngleBL: 's',
    roundAngleBR: 's',
    roundAngleTL: 's',
    roundAngleTR: 's',
    cursor: 'pointer',
    captionVAlign: 'top',
    captionHAlign: 'left',
    captionFontSize: 'xl',
    captionFontWeight: 'bold',
    descriptionVAlign: 'top',
    descriptionHAlign: 'left',
    descriptionFontSize: 'm',
    descriptionFontColorStyle: 'unaccented',
    shadowVisibility: 'visible',
    paddingTop: 's',
    paddingBottom: 's',
    paddingLeft: 's',
    paddingRight: 's',
};