const gridUnsupportedOptions: string[] = [
    'header',
    'footer',
    'emptyTemplateColumns',
    'emptyTemplateOptions',
    'groupViewMode',
    'itemEditorTemplate',
    'itemEditorTemplateOptions',
    'ladderMode',
    'resultsColspanCallback',
    'resultsTemplate',
    'resultsTemplateOptions',
    'resultsVisibility',
    'stickyColumnsCount',
    'draggingTemplate',
    'itemsDragNDrop',
    'itemTemplateOptions',
    'trackedProperties',
    'trackedPropertiesTemplate',
    'actionAlignment',
    'actionCaptionPosition',
    'contextMenuVisibility',
    'itemActionsClass',
    'attachLoadTopTriggerToNull',
    'backgroundStyle',
    'emptyTemplate',
    'fadedKeys',
    'footerTemplate',
    'hoverBackgroundStyle',
    'itemsSpacingVisibility',
    'iterativeLoadPageSize',
    'iterativeLoadTimeout',
    'keepScrollAfterReload',
    'moreButtonTemplate',
    'moreFontColorStyle',
    'multiSelectTemplate',
    'pixelRatioBugFix',
    'style',
    'subPixelArtifactFix',
    'urlProperty',
    'moveMarkerOnScrollPaging',
    'keyProperty',
    'placeholderAfterContent',
    'itemTemplateProperty',
    'groupTemplate',
];

const treeGridUnsupportedOptions: string[] = [
    'hasChildrenProperty',
    'nodeHistoryId',
    'nodeHistoryType',
    'nodeProperty',
    'parentProperty',
    'root',
    'selectionCountMode',
    'selectionType',
    'childrenCountProperty',
    'collapsedItems',
    'deepReload',
    'nodeFooterTemplate',
    'nodeFooterVisibilityCallback',
    'nodeHeaderTemplate',
    'nodeLoadCallback',
    'deepScrollLoad',
    'groupNodeVisibility',
];

const unsupportedProps = gridUnsupportedOptions.concat(treeGridUnsupportedOptions);

export default unsupportedProps;
