export default {
    '--background-color': '#424851',
    '--unaccented_background-color': '#3d424a',
    '--hover_background-color': '#464d57',
    '--text-color': '#cccccc',
    '--border-color': '#6b6b6b',
    '--separator_color': '#6b6b6b',
    '--icon-color': '#cccccc',
    '--contrast_icon-color': '#383d44',
    '--label_text-color': '#9EA8B2',
    '--label_hover_text-color': '#ccc',
    '--link_text-color': '#6ed4d0',
    '--link_hover_text-color': '#ff7033',

    '--primary_text-color': '#cccccc',

    '--secondary_color': '#6ed4d0',
    '--secondary_text-color': '#cccccc',
    '--secondary_hover_text-color': '#ff7033',
    '--secondary_hover_icon-color': '#ff7033',
    '--secondary_hover_color': '#5eb4b1',

    '--success_color': '#72be44',
    '--success_hover_color': '#4f9425',
    '--danger_color': '#d04d4d',
    '--danger_hover_color': '#b84040',

    '--warning_color': '#fec63f',

    '--primary_border-color_button': '#eb6c65',
    '--primary_hover_background-color_button': '#535c68',
    '--primary_active_background-color_button': '#535c68',
    '--secondary_hover_background-color_button': '#535c68',
    '--secondary_active_background-color_button': '#535c68',
    '--background-color_hover_button_toolButton': '#535c68',
    '--unaccented_contrast_background-color': '#6ed4d0',
    '--unaccented_hover_contrast_background-color': '#5eb4b1',
    '--unaccented_active_contrast_background-color': '#5eb4b1',
    '--pale_border-color': '#535c68',
    '--pale_hover_color': '#535c68',
    '--pale_active_color': '#535c68',
};
